version: '2'

services:
  app:
    image: 'chatvault:latest'
    build:
      context: .
      dockerfile: ./docker/spring.dockerfile
    depends_on:
      - docker_psql_db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    ports:
      - "1018:8080"

  docker_psql_db:
    image: 'postgres:13.1-alpine'
    build:
      context: .
      dockerfile: ./docker/postgres.dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chatvault

#  prometheus:
#    image: prom/prometheus:v2.38.0
#    container_name: prometheus-container
#    volumes:
#      - ./prometheus/:/etc/prometheus/
#      - ./prometheus/data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - "1029:9090"
#    restart: unless-stopped
#
#  grafana:
#    image: grafana/grafana-oss:9.1.4
#    container_name: grafana-container
#    depends_on:
#      - prometheus
#    ports:
#      - "1040:3000"
#    volumes:
#      - ./grafana/:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
#      - GF_SERVER_DOMAIN=localhost
