scrape_configs:
  - job_name: 'Kotlin Blog'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'app:8080' ]
  - job_name: 'Prometheus meta scraping'
    metrics_path: /metrics
    scrape_interval: 3s
    static_configs:
      - targets: [ 'localhost:9090' ]