version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: spring_dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kotlinblog
      - SPRING_DATASOURCE_USERNAME=composeOrElse
      - SPRING_DATASOURCE_PASSWORD=throwNewNull
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"

  db:
    image: 'postgres:13.1-alpine'
    build:
      context: .
      dockerfile: postgres_dockerfile
    container_name: db
    environment:
      - POSTGRES_USER=composeOrElse
      - POSTGRES_PASSWORD=throwNewNull
      - POSTGRES_DB=kotlinblog