name: Docker build and push
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create env.properties
        run: |
          touch env.properties
          printf "JDBC_PSQL_URI=jdbc:postgresql://host.docker.internal:5432/chatvault\nPSQL_USERNAME=postgres\nPSQL_PASSWORD=postgres" >> env.properties
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/spring.dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatvault:latest
            ghcr.io/zxisatree/chatvault:latest