name: Gradle test on Ubuntu
on: push
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: db_creator
          POSTGRES_PASSWORD: write
          POSTGRES_DB: kotlin_blog
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Check if Postgres is reachable
        run: |
          sudo apt install -y postgresql-client
          echo "Postgres installed"
          pg_isready
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Test with Gradle
        run: ./gradlew test --no-daemon
