name: Gradle test on Windows
on: push
jobs:
  windows_tests:
    runs-on: windows-latest
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: windows_tester
          password: postgres
          database: kotlin_blog
          port: 5432
        id: postgres
      - uses: actions/checkout@v3
      - name: Seed database
        run: |
          Copy-Item .github/env.properties -Destination ./
          $Env:PGPASSWORD="postgres"
          psql -h localhost -d kotlin_blog -U windows_tester -f .github/windows_seed.sql
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Test with Gradle
        run: ./gradlew test --no-daemon --info