name: Gradle test on Windows
on: push
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: composeOrElse
          password: throwNewNull
          database: kotlinblog
          port: 5432
        id: postgres
      - uses: actions/checkout@v3
      - name: Seed database
        run: PG_PASSWORD=throwNewNull psql -h localhost -d kotlin_blog -U composeOrElse -f ./docker/docker-entrypoint-initdb.d/init.sql
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Test with Gradle
        run: ./gradlew test --no-daemon