name: Gradle test
on: push
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14.7-alpine'
          POSTGRES_PASSWORD: db_creator
          POSTGRES_USER: write
          POSTGRES_DB: kotlin_blog
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Test with Gradle
        run: ./gradlew test --no-daemon